export const ADD_ALBUM = 'ADD_ALBUM';
export const DELETE_ABLUM = 'DELETE_ALBUM';
export const SEARCH_ABLUM_STARTED = 'SEARCH_ABLUM_STARTED';
export const SEARCH_ABLUM_SUCCESS = 'SEARCH_ALBUM_SUCCESS';
export const SEARCH_ABLUM_FAILURE = 'SEARCH_ALBUM_FAILURE';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
